services:
  mysql:
    image: mysql:8.0
    container_name: webgl_mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - db_password
    networks:
      - webgl_network
    expose:
      - "3306"
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webgl_webapp
    volumes:
      - webapp_logs:/var/log/apache2
    networks:
      - webgl_network
    depends_on:
      - mysql
    expose:
      - "80"
  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: webgl_auth
    environment:
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - auth_logs:/app/logs
    networks:
      - webgl_network
    depends_on:
      - mysql
    secrets:
      - db_password
    expose:
      - "3000"
  nginx:
    image: nginx:alpine
    container_name: webgl_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    networks:
      - webgl_network
    depends_on:
      - webapp
      - auth

volumes:
  mysql_data:
  webapp_logs:
  auth_logs:
  nginx_logs:

networks:
  webgl_network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt